Use tomllib/tomli/tomli-w instead of unmaintained toml [WIP]
getsentry/responses pull request #596
Opened 2022-10-12 11:26 UTC by mgorny

Replace the `toml` dependency that is unmaintained (last release in 2020) and does not implement TOML 1.0 with more modern libraries. Use the built-in `tomllib` module to load .toml files on Python 3.11, and its drop-in replacement `tomli` package on older versions of Python. For writing .toml files, use the `tomli-w` package.

2022-10-12 11:27 UTC, mgorny commented
There's one problem with this: right now it fails because it attempts to serialize `None` that has no valid representation in TOML. Apparently the buggy `toml` module either ignored keys with `None` as value or serialized it as string `"None"` (sic!).

2022-10-12 12:38 UTC, beliaev-maksim requested changes

2022-10-12 12:38 UTC, beliaev-maksim commented on responses/tests/test_recorder.py
> +import sys
```suggestion
```

2022-10-12 12:38 UTC, beliaev-maksim commented on responses/__init__.py
> +import sys
```suggestion
```

2022-10-12 12:42 UTC, beliaev-maksim commented
makes sense to switch. Thanks for the PR

at the time of writing the feature I chose `toml` because of the wider usage by the community. However, if it is unmaintained there is no reason not to go for `tomli`

will also resolve #595

2022-10-12 12:46 UTC, mgorny commented
> at the time of writing the feature I chose `toml` because of the wider usage by the community.

I'm surprised at that but I suppose there's still work to be done there. I think most of the major projects (black, flit, mypy, pytest, setuptools, tox to list just a few) have switched to `tomli` already. At least a quick glance it seems that `tomli` has more revdeps in Gentoo than `toml`.

2022-10-12 15:09 UTC, mgorny commented
See https://github.com/getsentry/responses/pull/596#issuecomment-1276008203. The problem is that the input is broken right now, and I'm looking for guidance what fix would you prefer for it.

2022-10-12 15:31 UTC, beliaev-maksim commented
> Apparently the buggy `toml` module either ignored keys with `None`

it is not buggy, but done on purpose
I just went over discussions on https://github.com/toml-lang/toml/issues/921
also, read threads in `tomli-w` and `toml`

according to toml-lang the value with null should not be present in the file, thus, it should be filtered out in languages where it is present eg python. So, we need to filter all nulls out.

```python
def remove_nones(d):
    if isinstance(d, dict):
        return {k: remove_nones(v) for k, v in d.items() if v is not None}
    return d
```

and then dump the result

2022-10-12 16:50 UTC, mgorny commented
Thanks for the snippet. Done that now and the tests seem to pass.

2022-10-14 19:34 UTC, merged

2022-10-14 19:34 UTC, markstory commented
Thank you 🎉

2022-10-15 06:32 UTC, mgorny commented
Thanks!

2022-10-29 13:20 UTC, mgorny commented
> we will add support for 3.11 once it is released please remove it so far

Python 3.11.0 has been released on Oct 24th.