ci(actions): Bump actions to resolve CI warnings
getsentry/responses pull request #605
Opened 2022-11-13 14:41 UTC by tony

[Example job](https://github.com/getsentry/responses/actions/runs/3329947398)

<details>

<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/26336/201527569-f9634237-7c7f-4b06-be2b-ce363b62da7b.png)

</details>

2022-11-13 14:52 UTC, beliaev-maksim requested changes

2022-11-13 14:52 UTC, beliaev-maksim commented on .github/workflows/ci.yml
> +    - uses: actions/setup-python@v3
```suggestion
    - uses: actions/setup-python@v4
```

2022-11-13 14:53 UTC, tony commented on .github/workflows/ci.yml
> +    - uses: actions/setup-python@v3
Good catch! Updated via rebase

2022-11-13 14:56 UTC, beliaev-maksim approved these changes

2022-11-13 15:37 UTC, tony commented
@beliaev-maksim I added one more bump via squash, @actions/checkout v2 -> v3. [job](https://github.com/getsentry/responses/actions/runs/3455737130),  [release notes](https://github.com/actions/checkout/releases/tag/v3.0.0)

2022-11-14 22:08 UTC, merged

2022-11-14 22:08 UTC, markstory commented
Thank you 🎉