fix(matchers): Don't sort failed matches when printing error message
getsentry/responses pull request #711
Opened 2024-04-26 13:22 UTC by mgaligniana

Fixes GH-704

2024-04-26 13:27 UTC, beliaev-maksim commented
@markstory I think we introduced `_create_key_val_str` for the compatibility between python2 and python3

should we just drop it completely and just present JSON?

2024-04-26 13:27 UTC, beliaev-maksim commented
@mgaligniana please add changelog file entry

2024-04-26 13:30 UTC, mgaligniana commented
@beliaev-maksim thank you for your fast response! On it! :factory_worker:

2024-04-26 13:40 UTC, mgaligniana commented
@beliaev-maksim Done! Let me know if message is OK (I'm not English native speaker). Feel free to suggest changes! Thank you!

2024-04-29 19:24 UTC, markstory commented
> I think we introduced _create_key_val_str for the compatibility between python2 and python3 should we just drop it completely and just present JSON?

I think you're right on the origin of that method. We could likely drop it now that we're not supporting python 2 anymore.

2024-04-29 19:48 UTC, mgaligniana commented
@markstory Do you want me to tackle in this pull request? Or in another ticket?

2024-04-29 20:11 UTC, beliaev-maksim commented
@mgaligniana yes please

2024-04-29 21:17 UTC, markstory commented
> Do you want me to tackle in this pull request? Or in another ticket?

Either works for me. Using this pull request would be simpler for us though.

2024-04-30 04:42 UTC, mgaligniana commented
Done!

I had to update all test cases because now it shows inputs are strings in error messages.

For example in `query_param_matcher`
Before: `...doesn't match {array: [B, A, C]}` After: `...doesn't match: {'array': ['B', 'A', 'C']}`

2024-04-30 06:19 UTC, beliaev-maksim requested changes

2024-04-30 06:19 UTC, beliaev-maksim commented on CHANGES
> +* Delete `_create_key_val_str` which was introduced for the compatibility between python2 (not supported anymore) and python3.
I would not talk about internal method. Instead, please briefly describe what changed for the end user

2024-04-30 14:15 UTC, mgaligniana commented
> I would not talk about internal method. Instead, please briefly describe what changed for the end user

Makes sense!

Ready, thanks for your help and patience!

2024-04-30 14:18 UTC, beliaev-maksim approved these changes

2024-04-30 14:18 UTC, beliaev-maksim commented
looks good, thanks

2024-04-30 20:41 UTC, markstory commented
There are a few failing tests that will need to be addressed before this could be merged.

2024-04-30 21:16 UTC, mgaligniana commented
> There are a few failing tests that will need to be addressed before this could be merged.

Will star working on that! I'm going to use `tox` to can reproduce them! 👷 🚧

2024-05-01 02:57 UTC, mgaligniana commented
Now it is! I missed a f-string and probably forgot run the tests before push 🤷, sorry!

2024-05-06 19:26 UTC, mgaligniana commented
@markstory sorry for the direct ping! But could you re-run the tests? Thank you!

2024-05-08 14:41 UTC, merged

2024-05-08 14:41 UTC, markstory commented
Thank you 🎉